#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Ryuichi Ueda <keigo0918enjoy@gmail.com>

import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)    
